### ISSUE TITLE
springboot(二)：web综合开发 - 纯洁的微笑博客

### ISSUE THREAD

**Issue by ityouknow** [ityouknow/blog-comments#153]
http://www.ityouknow.com/springboot/2016/02/03/spring-boot-web.html 

 <p>上篇文章介绍了Spring boot初级教程：<a href="http://www.ityouknow.com/springboot/2016/01/06/springboot(%E4%B8%80)-%E5%85%A5%E9%97%A8%E7%AF%87.html">spring boot(一)：入门篇</a>，方便大家快速入门、了解实践Spring boot特性；本篇文章接着上篇内容继续为大家介绍spring boot的其它特性（有些未必是spring boot体系桟的功能，但是是spring特别推荐的一些开源技术本文也会介绍），对了这里只是一个大概的介绍，特别详细的使用我们会在其它的文章中来展开说明。</p>

**Comment by gaoKyle** [comment]
很不错

**Comment by Han-China** [comment]
再看一遍

**Comment by Jedeiah** [comment]
你个尿性用的很尿性啊

**Comment by lessoon** [comment]
提个小BUG，在该页面点【spring boot(一)：入门篇】连接会跳到 【All articles are here ： http://www.ityouknow.com/springboot/2016/01/06/springboot(一)-入门篇.html】页面

**Comment by ityouknow** [comment]
> @lessoon
> 提个小BUG，在该页面点【spring boot(一)：入门篇】连接会跳到 【All articles are here ： http://www.ityouknow.com/springboot/2016/01/06/springboot(一)-入门篇.html】页面

感谢反馈，这个问题解决了。

**Comment by xiaolu991954992** [comment]
您好，请问一下配置信息通过@Value自动注入的时候，中文信息会产生乱码，怎么解决呀？

**Comment by whatalittlebear** [comment]
> @xiaolu991954992
> 您好，请问一下配置信息通过@Value自动注入的时候，中文信息会产生乱码，怎么解决呀？

我也是这个问题，希望大侠们指点下，我的配置文件编码改成utf-8了，但是断点跑的时候，看到代码处获得的值的确乱码了，好纠结。。我的是eclipse

**Comment by sdcjj** [comment]
> @whatalittlebear
> > @xiaolu991954992
> > 您好，请问一下配置信息通过@Value自动注入的时候，中文信息会产生乱码，怎么解决呀？
> 
> 我也是这个问题，希望大侠们指点下，我的配置文件编码改成utf-8了，但是断点跑的时候，看到代码处获得的值的确乱码了，好纠结。。我的是eclipse


> @whatalittlebear
> > @xiaolu991954992
> > 您好，请问一下配置信息通过@Value自动注入的时候，中文信息会产生乱码，怎么解决呀？
> 
> 我也是这个问题，希望大侠们指点下，我的配置文件编码改成utf-8了，但是断点跑的时候，看到代码处获得的值的确乱码了，好纠结。。我的是eclipse

加这个配置
spring.http.encoding.charset=UTF-8

**Comment by Jedeiah** [comment]
自定义工具类 
1 重写MySQL5Dialect的getTableTypeString方法，修改创建数据库时候的编码（ta默认库的编码是iso8859-1）
2 插入数据时候，需指定编码，mysql5.6需在my.ini文件中指定。（在idea的spring boot框架的配置文件中引入不管用-待思考）
我给你赋上工具类截图。 




发送自 Windows 10 版邮件应用

发件人: whatalittlebear
发送时间: 2018年8月8日 11:24
收件人: ityouknow/blog-comments
抄送: Jedeiah; Comment
主题: Re: [ityouknow/blog-comments] springboot(二)：web综合开发 - 纯洁的微笑博客 (#153)

@xiaolu991954992
您好，请问一下配置信息通过@value自动注入的时候，中文信息会产生乱码，怎么解决呀？
我也是这个问题，希望大侠们指点下，我的配置文件编码改成utf-8了，但是断点跑的时候，看到代码处获得的值的确乱码了，好纠结。。我的是eclipse

**Comment by Etnen** [comment]
挺不错的，那个你每个类展示的时候也把上面导入的包也展示一下。有时候导入时不知道是哪个。谢谢，就是类似这种
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

**Comment by daguang08** [comment]
### 不错

**Comment by bihell** [comment]
综合开发的代码运行报错。。。需要帮助

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource [org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketException: Broken pipe (Write failed); nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe (Write failed)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.10.RELEASE.jar:4.3.1

**Comment by bajie2** [comment]
对于我来说(使用maven的人)，少讲了最重要的几点，thymeleaf模板要放在哪个文件夹？还要进行哪些配置，controller才能使用它？

**Comment by Qk1hpys** [comment]
说实话Thymeleaf实际生产中使用到吗？现在不还是前端后端分离的大趋势吗，前端框架+后端开放接口？

**Comment by ityouknow** [comment]
@Qk1hpys 用的到

**Comment by iyinghui** [comment]
看起来不错，学习了，希望作者努力写出更多更详细的相关博客。

**Comment by will0211** [comment]
感谢博主无私分享！
我分享一些免费的springboot视频教程给大家
Java 微服务实践 - Spring Boot 视频: http://www.chilangedu.com/course/1489582623.html
Java 微服务实践 - Spring Cloud 视频: http://www.chilangedu.com/course/1606928230.html

**Comment by aloneDesperado** [comment]
给个建议，能不能把引包也写在上面

**Comment by tunglee5420** [comment]
为什么没有注入数据库表名

**Comment by daimengyang** [comment]
> @JustGeeker
> 为什么没有注入数据库表名
> 

public interface UserRepository extends JpaRepository<User, Long> 
泛型里有了

**Comment by harryas** [comment]
> @aloneDesperado
> 给个建议，能不能把引包也写在上面

github里面有代码呢。不过就是没写明对应的是哪个

**Comment by RainyBlossom** [comment]
spring 项目建议使用Gradle进行构建项目，相比maven来讲 Gradle更简洁，而且gradle更时候大型复杂项目的构建。gradle吸收了maven和ant的特点而来，不过目前maven仍然是Java界的主流，大家可以先了解了解。
---------
更适合写成更时候了

**Comment by hzqhi** [comment]
> @bihell
> 综合开发的代码运行报错。。。需要帮助
> 
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource [org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketException: Broken pipe (Write failed); nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe (Write failed)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.10.RELEASE.jar:4.3.1

**Comment by hzqhi** [comment]
老哥参考这个链接https://www.cnblogs.com/gudi/p/7823557.html，再修改Redis 本机地址spring.redis.host=127.0.0.1，即可

**Comment by tianzhen155** [comment]
> @whatalittlebear
> > @xiaolu991954992
> > 您好，请问一下配置信息通过@Value自动注入的时候，中文信息会产生乱码，怎么解决呀？
> 
> 我也是这个问题，希望大侠们指点下，我的配置文件编码改成utf-8了，但是断点跑的时候，看到代码处获得的值的确乱码了，好纠结。。我的是eclipse

**Comment by tianzhen155** [comment]
> 您好，请问一下配置信息通过@value自动注入的时候，中文信息会产生乱码，怎么解决呀？

是配置文件的格式问题，你写一个测试方法，就测试配置文件的中文是否能输出你想要的字符格式

**Comment by xiaoyunhe-coldcast** [comment]
很不错的文章，点个赞

**Comment by Traserve** [comment]
为什么文章没有关联下一篇文章的链接呀

**Comment by tianjiwuhen7** [comment]
WebJars主官网 ""链接失效了吧

**Comment by jamescommoncoder** [comment]
请问一下能提供一些数据库脚本吗?github包括博客上只有代码没有sql文件@ityouknow

**Comment by tianjiwuhen7** [comment]
你好！


这个不需要数据库脚本，你只要建库，把数据库名字替换，就会自动生成表结构。（下图test为数据库名）





------------------ 原始邮件 ------------------
发件人: "zhoubinbin19920601"<notifications@github.com>;
发送时间: 2019年5月26日(星期天) 晚上7:23
收件人: "ityouknow/blog-comments"<blog-comments@noreply.github.com>;
抄送: "天际"<937483818@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ityouknow/blog-comments] springboot(二)：web综合开发 - 纯洁的微笑博客 (#153)




请问一下能提供一些数据库脚本吗?github包括博客上只有代码没有sql文件@ityouknow

**Comment by ExecutiveOfficer** [comment]
> @shandongcjiajia
> > @whatalittlebear
> > > @xiaolu991954992
> > > 您好，请问一下配置信息通过@Value自动注入的时候，中文信息会产生乱码，怎么解决呀？
> > 
> > 我也是这个问题，希望大侠们指点下，我的配置文件编码改成utf-8了，但是断点跑的时候，看到代码处获得的值的确乱码了，好纠结。。我的是eclipse
> 
> 
> > @whatalittlebear
> > > @xiaolu991954992
> > > 您好，请问一下配置信息通过@Value自动注入的时候，中文信息会产生乱码，怎么解决呀？
> > 
> > 我也是这个问题，希望大侠们指点下，我的配置文件编码改成utf-8了，但是断点跑的时候，看到代码处获得的值的确乱码了，好纠结。。我的是eclipse
> 
> 加这个配置
> spring.http.encoding.charset=UTF-8

把SpringBoot的主配置文件改成yml格式的就行

**Comment by xinghuili** [comment]
##大佬，膜拜！！

**Comment by Hyuga-Neji** [comment]
在UserRepositoryTests测试类中，UserRepository应该无法被注入进来吧，它是一个接口，没有任何注解和配置表明它是一个SpringBean啊。我看了github上面的源码，也没有写。

**Comment by yuzhihaoGitHub** [comment]
我想说看完这章怎么进入下一张

**Comment by yibinxueyuan** [comment]
Caused by: java.lang.IllegalStateException: Cannot load driver class: com.mysql.cj.jdbc.Driver?serverTimezone=UTC

**Comment by fdl158** [comment]
@Bean
    public FilterRegistrationBean filterRegistrationBean() {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(new MyFilter());
        registration.addUrlPatterns("/*");
        registration.addInitParameter("paramName", "paramValue");
        registration.setName("MyFilter");
        registration.setOrder(1);
        return registration;

    }

这里的new MyFilter()  有问题吧

**Comment by ExecutiveOfficer** [comment]
有什么问题?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "deling"<notifications@github.com&gt;; 
发送时间: 2019年11月27日(星期三) 晚上11:03
收件人: "ityouknow/blog-comments"<blog-comments@noreply.github.com&gt;; 
抄送: "自己～"<614289233@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ityouknow/blog-comments] springboot(二)：web综合开发 - 纯洁的微笑博客 (#153)




@bean
 public FilterRegistrationBean filterRegistrationBean() {
 FilterRegistrationBean registration = new FilterRegistrationBean();
 registration.setFilter(new MyFilter());
 registration.addUrlPatterns("/*");
 registration.addInitParameter("paramName", "paramValue");
 registration.setName("MyFilter");
 registration.setOrder(1);
 return registration;
 }  
这里的new MyFilter()  有问题吧

**Comment by yuzhihaoGitHub** [comment]
你好。这个是我之前好久看到的，那个时候觉着有问题提了下，到现在有些忘了，不好意思哈。我经常上你网站，今天还关注了你公众号，是你的粉丝哈哈哈------------------ 原始邮件 ------------------
发件人: "ExecutiveOfficer"<notifications@github.com>
发送时间: 2019年11月28日(星期四) 下午5:20
收件人: "ityouknow/blog-comments"<blog-comments@noreply.github.com>;
抄送: "yuzhihaoGitHub"<759620498@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ityouknow/blog-comments] springboot(二)：web综合开发 - 纯洁的微笑博客 (#153)


有什么问题? 
 
 
 
 
 ------------------&nbsp;原始邮&#x4EF6;&nbsp;------------------ 
 发&#x4EF6;人: "deling"<notifications@github.com&gt;;  
 发送时间: 2019年11月27日(星期三) 晚上11:03 
 收&#x4EF6;人: "ityouknow/blog-comments"<blog-comments@noreply.github.com&gt;;  
 抄送: "自己～"<614289233@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;;  
 主题: Re: [ityouknow/blog-comments] springboot(&#x4E8C;)：web综合开发 - 纯洁的微笑博客 (#153) 
 
 
 
 
 @bean 
  public FilterRegistrationBean filterRegistrationBean() { 
  FilterRegistrationBean registration = new FilterRegistrationBean(); 
  registration.setFilter(new MyFilter()); 
  registration.addUrlPatterns("/*"); 
  registration.addInitParameter("paramName", "paramValue"); 
  registration.setName("MyFilter"); 
  registration.setOrder(1); 
  return registration; 
  }   
 这里的new MyFilter()  有问题吧 
   
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by xKimi** [comment]
【WebJars主官网】链接无效了
