### ISSUE TITLE
springboot(一)：入门篇 - ityouknow's Blog

### ISSUE THREAD

**Issue by ityouknow** [ityouknow/blog-comments#34]
http://www.ityouknow.com/springboot/2016/01/06/springboot(%E4%B8%80)-%E5%85%A5%E9%97%A8%E7%AF%87.html 

 什么是spring boot

**Comment by EndlessSarrow** [comment]
您写的太TM好了

**Comment by EndlessSarrow** [comment]
但是HelloWorldController中是不是还需要个@EnableAutoConfiguration

**Comment by ityouknow** [comment]
> @EndlessSarrow
>  但是HelloWorldController中是不是还需要个@EnableAutoConfiguration

不需要

**Comment by zzzccc129** [comment]
我必须的说点什么了,您写的真是TM好了,就像您图片所说,我真是TM日了狗了额

**Comment by GongFuXiaoZi** [comment]
我必须的说点什么了,您写的真是TM好了,就像您图片所说,我真是TM日了狗了额

**Comment by fish-cai** [comment]
额 。。有个奇怪的地方status().isOk()，这个地方的调用感觉有点迷，静态引用吗？

**Comment by ityouknow** [comment]
> @532798554
> 额 。。有个奇怪的地方status().isOk()，这个地方的调用感觉有点迷，静态引用吗？

是静态引用。

**Comment by fish-cai** [comment]
> @ityouknow
> > @532798554
> > 额 。。有个奇怪的地方status().isOk()，这个地方的调用感觉有点迷，静态引用吗？
> 
> 是静态引用。

好的  谢谢。

**Comment by crazyangle** [comment]
简明扼要，快速入门，希望有高阶教学

**Comment by iliguo** [comment]
> @EndlessSarrow
> 您写的太TM好了

写的的确过于太tm好了
> @EndlessSarrow
> 您写的太TM好了

> @GongFuXiaoZi
> 我必须的说点什么了,您写的真是TM好了,就像您图片所说,我真是TM日了狗了额

楼主想必是一个超级牛人

**Comment by ShanatoYuuji** [comment]
老哥，太TM叼了。

**Comment by qingqianxuewei** [comment]
太赞了～

**Comment by shihp** [comment]
666 学习了.

开发环境的调试这块我修改代码没有生效.

```
<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <fork>true</fork>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by xiongzhao1217** [comment]
文章写得很棒，排版也很棒，读起来很舒服，如果能使用intellij做演示就更好了

**Comment by ityouknow** [comment]
> @shihp
> 666 学习了.
> 
> 开发环境的调试这块我修改代码没有生效.
> 
> ```
> <build>
>         <plugins>
>             <plugin>
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-maven-plugin</artifactId>
>                 <configuration>
>                     <fork>true</fork>
>                 </configuration>
>             </plugin>
>         </plugins>
>     </build>
> ```
> 
> 

idea需要单独配置，可以看我达人课里面的文章。

**Comment by zhangqingyun123** [comment]
@Test
public void getWang() throws Exception {
	System.out.println("name = " + name);
	mvc.perform(MockMvcRequestBuilders.get("/wang").accept(MediaType.APPLICATION_JSON))
			.andExpect(status().isOk())
			.andExpect(content().string(equalTo("zqy wang wang wang")));
}
如果在controller接口中用@Value注解注入的属性拿不到，但是不用Junit测试，而是直接启动程序的话，用网页访问又是可以拿到的，为什么？？？

**Comment by ityouknow** [comment]
> @xiongzhao1217
> 文章写得很棒，排版也很棒，读起来很舒服，如果能使用intellij做演示就更好了
达人课系列是用intellij做的演示：http://gitbook.cn/gitchat/column/59f5daa149cd4330613605ba

**Comment by wangyequn** [comment]
需要对Spring boot有什么深度的理解,才能写出这种文章啊,感觉您的文字读起来逻辑严密,条理清晰,重点明确,如沐春风,非常感谢,收藏网址了~

**Comment by cloud13th** [comment]
您写的太TM好了

**Comment by molingyu123** [comment]
我怎么没有弄好版本都不对

**Comment by molingyu123** [comment]
写的是不是少了点什么东西，从项目生成器我的版本我用的是1.5 在pom.xml里面添加你提供的出现了报错，显示版本的问题

**Comment by weizhile** [comment]
我必须的说点什么了,您写的真是TM好了,就像您图片所说,我真是TM日了狗了额

**Comment by lafeier888** [comment]
mark

**Comment by elite2012** [comment]
java 1.8  maven 3.39 springboot 2.00
Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.0.0.RELEASE:run (default-cli) on project dd: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.0.0.RELEASE:run failed: Unable to find a single main class from the following candidates [Application, com.example.dd.DdApplication] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by nameFH** [comment]
请问为什么在http://start.spring.io/生成的项目不能不能导入到myeclipse

**Comment by Ruanyifei** [comment]
热加载引入了jar包和plugs怎么没有生效啊？

**Comment by chenallen1025** [comment]
1、Application.java 建议放到根目录下面,主要用于做一些框架配置
----这句话的深层意思，springboot 只扫描Application包及其子包下的Controller、Configuration 等注解。不然其他包的controller就不能访问了.

**Comment by ysuzalmon** [comment]
我敢确定在座的各位95%以上都是用Github帐号登录的

**Comment by ysuzalmon** [comment]
> @Ruanyifei
> 热加载引入了jar包和plugs怎么没有生效啊？

还需要做：
更改idea配置
　　1） “File” -> “Settings” -> “Build,Execution,Deplyment” -> “Compiler”，选中打勾 “Build project automatically” 。
　　2） 组合键：“Shift+Ctrl+Alt+/” ，选择 “Registry” ，选中打勾 “compiler.automake.allow.when.app.running” 。
 Chrome禁用缓存
　　F12或者“Ctrl+Shift+I”，打开开发者工具，“Network” 选项卡下 选中打勾 “Disable Cache(while DevTools is open)”

**Comment by ghost** [comment]
使用idea ，artifactId 不能叫spring-boot，不然热启动不好用。

**Comment by yangwenbinGit** [comment]
写的挺好的 但是.andExpect(status().isOk())
                .andExpect(content().string(equalTo("Hello World")));  那个status这个方法没有找到。不知道为啥，这个方法是在那个private MockMvc mvc;中吗 还是在哪里呢

**Comment by starwavelin** [comment]
> @yangwenbinGit
> 写的挺好的 但是.andExpect(status().isOk())
>                 .andExpect(content().string(equalTo("Hello World")));  那个status这个方法没有找到。不知道为啥，这个方法是在那个private MockMvc mvc;中吗 还是在哪里呢

status()方法源自如下：
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

**Comment by starwavelin** [comment]
不过大牛们，我测试的时候是equalTo()方法找不到
```
.andExpect(content().string(equalTo("Hello World")));
```
IntelliJ也提示不到我应该import什么包，麻烦给点提示，谢谢！ @yangwenbinGit @ityouknow

**Comment by itmyhome2013** [comment]
开始跟随大师的节奏 学习 sprig boot

**Comment by ityouknow** [comment]
> @itmyhome2013
> 开始跟随大师的节奏 学习 sprig boot

哈哈 麦田你好。

**Comment by e7** [comment]
> @starwavelin
> 不过大牛们，我测试的时候是equalTo()方法找不到
> ```
> .andExpect(content().string(equalTo("Hello World")));
> ```
> IntelliJ也提示不到我应该import什么包，麻烦给点提示，谢谢！ @yangwenbinGit @ityouknow

import static org.hamcrest.Matchers.equalTo;

**Comment by myflx** [comment]
> @ityouknow
请教一下测试报这个错误什么原因？
java.lang.AssertionError: Status expected:<200> but was:<404>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.servlet.result.StatusResultMatchers.lambda$matcher$9(StatusResultMatchers.java:617)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:178)
	at com.example.demo.HelloTests.getHello(HelloTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by ctrl-alt-xxh** [comment]
编写测试类时，需引入如下三个内容：
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.hamcrest.Matchers.equalTo;

**Comment by ZGB0414** [comment]
很棒，我是一名初学者，很快地进行操作。谢谢你，已关注公众号

**Comment by wotoutengleha** [comment]
您写的太他妈好了

**Comment by JustDoNow** [comment]
给大佬点烟
